### ISSUE TITLE
[1.20.1] Blocks vary in size/offset, rather than behaving like normal blocks.

### ISSUE THREAD

**Issue by Alissa95** [nvb-uy/sod-fabric#11]
Minecraft version 1.20.1
Forge version 47.2.0

Sod blocks not behaving like normal blocks. Size and offset varies. Even with no other mods or resourcepacks installed.

![2023-10-09_12 31 36](https://github.com/nvb-uy/Grass-Overhaul/assets/109599123/0ae6d974-893b-472c-beac-1f969e6d6e23)

Also there is no creative tab and they don't appear in JEI, so I have to guess the recipes.

**Comment by nvb-uy** [comment]
Fixed in v23.10.10
